apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat-service
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - image: ahhmedhs/project-chat-service
          name: chat-service
          ports:
            - containerPort: 8070
            env:
            - name: servername_eureka
              value: "eureka-server"
      hostname: localhost
      restartPolicy: Always
